### ISSUE TITLE
Error when update!

### ISSUE THREAD

**Issue by exaline-ru** [leeliwei930/godspeed-essentials#1]
Update failed
"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json not null, `fields` json not null, `created_at` timestamp null, `updated_at`' at line 1 (SQL: create table `godspeed_essentials_q_r_codes` (`id` int unsigned not null auto_increment primary key, `resource_name` varchar(191) not null, `page` varchar(191) not null, `slugs` json not null, `fields` json not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB)" on line 664 of \vendor\laravel\framework\src\Illuminate\Database\Connection.php

**Comment by leeliwei930** [comment]
Hi @exaline-ru can you provide the system.log file to let me have a look with it.

**Comment by leeliwei930** [comment]
@exaline-ru , may I know what version of the MySQL are you using? the issue seems to be your MySQL server is below version 5.7.8 and doesn't support the JSON data type fields.

**Comment by exaline-ru** [comment]
Thank! After updating Mysql, the installation was successful.

Now there is a new error when creating the product:

![image](https://user-images.githubusercontent.com/46493161/82746668-11a8fa80-9d9b-11ea-8cd9-b2fe26e575e4.png)

**Comment by leeliwei930** [comment]
@exaline-ru Update is on its way please check for it about 3 minutes for version 1.1.5.
